import XCTest
@testable import RemoteCrabCore

/// Cross-language transport vectors (F1 task 2).
///
/// The fixture fixes the **ciphertext** for known inputs so the Rust end
/// (`rc-protocol`) can assert byte-for-byte the same output — the only real
/// proof the two implementations agree. Run with `REMOTECRAB_GEN_VECTORS=1`
/// to regenerate the JSON from this code (the source of truth).
final class TransportVectorsTests: XCTestCase {

    struct Vector: Codable, Equatable {
        let token: String
        let initiatorNonceHex: String
        let responderNonceHex: String
        let kind: UInt8
        let plaintextHex: String
        let sealedHex: String       // nonce ‖ ciphertext ‖ tag
    }

    /// The fixture is generated by `testGenerateVectors`; both ends load it.
    private static func fixtureURL() -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/transport-vectors.json")
    }

    static let inputs: [Vector] = [
        Vector(token: "RemoTok", initiatorNonceHex: "010203040506", responderNonceHex: "0a0b0c",
               kind: 0x13, plaintextHex: Data("RemoteCrab-e2e-OK".utf8).hex, sealedHex: ""),
        Vector(token: "another-token", initiatorNonceHex: "aabbccddeeff", responderNonceHex: "1122334455",
               kind: 0x04, plaintextHex: Data([0x00, 0x01, 0xff, 0x10, 0x20]).hex, sealedHex: ""),
    ]

    private func seal(_ v: Vector) -> String {
        let key = TransportCipher.sessionKey(token: v.token,
                                             initiatorNonce: Data(hexString: v.initiatorNonceHex),
                                             responderNonce: Data(hexString: v.responderNonceHex))
        var sealer = TransportCipher.Sealer(key: key)
        return sealer.seal(Data(hexString: v.plaintextHex), kind: v.kind).hex
    }

    func testGenerateVectors() throws {
        guard ProcessInfo.processInfo.environment["REMOTECRAB_GEN_VECTORS"] == "1" else {
            throw XCTSkip("set REMOTECRAB_GEN_VECTORS=1 to (re)generate the fixture")
        }
        let filled = Self.inputs.map { v in
            Vector(token: v.token, initiatorNonceHex: v.initiatorNonceHex, responderNonceHex: v.responderNonceHex,
                   kind: v.kind, plaintextHex: v.plaintextHex, sealedHex: seal(v))
        }
        let data = try JSONEncoder().encode(filled)
        print("VECTORS_JSON:" + String(data: data, encoding: .utf8)!)
    }

    func testFixtureVectorsMatch() throws {
        let data = try Data(contentsOf: Self.fixtureURL())
        let vectors = try JSONDecoder().decode([Vector].self, from: data)
        XCTAssertFalse(vectors.isEmpty)
        for v in vectors {
            XCTAssertEqual(seal(v), v.sealedHex, "seal mismatch for token \(v.token)")
        }
    }
}
